# Generated by Django 5.2.3 on 2025-07-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, null=True)),
                ('ap_paterno', models.CharField(blank=True, null=True)),
                ('ap_materno', models.CharField(blank=True, null=True)),
                ('correo', models.CharField(blank=True, null=True, unique=True)),
                ('curp', models.BinaryField(blank=True, null=True)),
                ('ine', models.BinaryField(blank=True, null=True)),
                ('foto', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'candidato',
                'managed': False,
            },
        ),
    ]
