# Generated by Django 5.2.3 on 2025-07-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admn_panel', '0002_ceec_ec_usuario_alter_candidato_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidato',
            table='candidato',
        ),
        migrations.AlterModelTable(
            name='grupo',
            table='grupo',
        ),
        migrations.AlterModelTable(
            name='infoprocesocandidato',
            table='info_proceso_candidato',
        ),
    ]
