# Generated by Django 5.2.3 on 2025-07-14 23:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoProcesoCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('portada', models.BinaryField(blank=True, null=True)),
                ('indice', models.BinaryField(blank=True, null=True)),
                ('carta_recepcion_docs', models.BinaryField(blank=True, null=True)),
                ('fecha_registro_generado', models.DateField(blank=True, null=True)),
                ('reporte_autenticidad', models.BinaryField(blank=True, null=True)),
                ('triptico_derechos_img', models.BinaryField(blank=True, null=True)),
                ('plan_evaluacion', models.BinaryField(blank=True, null=True)),
                ('encuesta_satisfaccion', models.BinaryField(blank=True, null=True)),
                ('instrumento_evaluacion', models.BinaryField(blank=True, null=True)),
                ('cedula_evaluacion', models.BinaryField(blank=True, null=True)),
                ('id_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admn_panel.candidato')),
                ('id_grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admn_panel.grupo')),
            ],
        ),
    ]
