# Generated by Django 5.2.3 on 2025-07-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admn_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeEc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ce', models.IntegerField(blank=True, null=True)),
                ('id_ec', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ce_ec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre del estándar')),
                ('codigo', models.TextField(verbose_name='Código del estándar')),
                ('id_examen_diagnostico', models.IntegerField(verbose_name='ID Examen Diagnóstico')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Estándar de Competencia',
                'verbose_name_plural': 'Estándares de Competencia',
                'db_table': 'estandar_de_competencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255, unique=True, verbose_name='Nombre de usuario')),
                ('contrasena', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('id_centro_evaluador', models.IntegerField(blank=True, null=True, verbose_name='ID Centro Evaluador')),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='candidato',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='infoprocesocandidato',
            options={'managed': False},
        ),
    ]
